<?php

namespace Toolkit\Currency\Export;

/**
 * تولید گزارش PDF ساده از تبدیل ارز
 * 
 * ایجاد فایل PDF با استفاده از کدهای PHP خالص (بدون کتابخانه خارجی)
 * 
 * @package Toolkit\Currency\Export
 * @author Toolkit Team
 * @version 1.2.0
 */
class PdfReportGenerator
{
    /**
     * عرض صفحه
     */
    private int $pageWidth = 595; // A4 width in points

    /**
     * ارتفاع صفحه
     */
    private int $pageHeight = 842; // A4 height in points

    /**
     * حاشیه‌ها
     */
    private int $margin = 40;

    /**
     * تولید گزارش PDF ساده
     * 
     * @param array $conversions آرایه‌ای از داده‌های تبدیل
     * @param string $title عنوان گزارش
     * @return string محتوای PDF به صورت binary
     */
    public function generate(array $conversions, string $title = 'Currency Conversion Report'): string
    {
        // ساختار PDF ساده
        $objects = [];
        $objectIndex = 1;

        // Catalog
        $catalogId = $objectIndex++;
        $objects[$catalogId] = "<< /Type /Catalog /Pages " . $objectIndex . " 0 R >>";

        // Pages
        $pagesId = $objectIndex++;
        
        // Content stream
        $contentId = $objectIndex++;
        $content = $this->buildContent($conversions, $title);
        $compressedContent = gzdeflate($content);
        $objects[$contentId] = "<< /Length " . strlen($content) . " /Filter /FlateDecode >>\nstream\n" . $compressedContent . "\nendstream";

        // Font
        $fontId = $objectIndex++;
        $objects[$fontId] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";

        // Page
        $pageId = $objectIndex++;
        $objects[$pageId] = "<< /Type /Page /Parent {$pagesId} 0 R /MediaBox [0 0 {$this->pageWidth} {$this->pageHeight}] /Contents {$contentId} 0 R /Resources << /Font << /F1 {$fontId} 0 R >> >> >>";

        $objects[$pagesId] = "<< /Type /Pages /Kids [{$pageId} 0 R] /Count 1 >>";

        // Build PDF
        $pdf = "%PDF-1.4\n";
        $xref = [];
        
        foreach ($objects as $id => $obj) {
            $xref[$id] = strlen($pdf);
            $pdf .= "{$id} 0 obj\n{$obj}\nendobj\n";
        }

        // Xref table
        $xrefOffset = strlen($pdf);
        $pdf .= "xref\n0 " . ($objectIndex) . "\n";
        $pdf .= "0000000000 65535 f \n";
        
        for ($i = 1; $i < $objectIndex; $i++) {
            $pdf .= str_pad($xref[$i], 10, '0', STR_PAD_LEFT) . " 00000 n \n";
        }

        // Trailer
        $pdf .= "trailer\n<< /Size " . $objectIndex . " /Root {$catalogId} 0 R >>\n";
        $pdf .= "startxref\n{$xrefOffset}\n%%EOF";

        return $pdf;
    }

    /**
     * ساخت محتوای صفحه
     */
    private function buildContent(array $conversions, string $title): string
    {
        $y = $this->pageHeight - $this->margin;
        $x = $this->margin;
        
        $content = "BT\n/F1 18 Tf\n";
        $content .= "{$x} {$y} Td\n(" . $this->escapePdf($title) . ") Tj\nET\n";
        
        $y -= 40;
        
        // Header row
        $content .= "BT\n/F1 12 Tf\n";
        $headers = ['Amount', 'From', 'To', 'Rate', 'Result', 'Date'];
        $colWidths = [80, 60, 60, 100, 100, 120];
        $colX = [$x, $x + 80, $x + 140, $x + 200, $x + 300, $x + 400];
        
        foreach ($headers as $i => $header) {
            $content .= "{$colX[$i]} {$y} Td\n(" . $this->escapePdf($header) . ") Tj\n";
        }
        
        $y -= 25;
        
        // Data rows
        $content .= "/F1 10 Tf\n";
        foreach ($conversions as $conv) {
            $row = [
                number_format($conv['amount'] ?? 0, 2),
                $conv['from'] ?? '',
                $conv['to'] ?? '',
                number_format($conv['rate'] ?? 0, 6),
                number_format($conv['result'] ?? 0, 2),
                date('Y-m-d H:i:s', $conv['timestamp'] ?? time())
            ];
            
            foreach ($row as $i => $value) {
                $content .= "{$colX[$i]} {$y} Td\n(" . $this->escapePdf($value) . ") Tj\n";
            }
            
            $y -= 18;
            
            // جلوگیری از خروج از صفحه
            if ($y < $this->margin + 50) {
                break;
            }
        }
        
        // Footer
        $y = $this->margin - 20;
        $content .= "/F1 8 Tf\n";
        $content .= "{$x} {$y} Td\n(Generated by Currency Converter v1.2.0) Tj\n";
        
        return $content;
    }

    /**
     * فرار کردن کاراکترهای خاص برای PDF
     */
    private function escapePdf(string $text): string
    {
        return str_replace(
            ['\\', '(', ')'],
            ['\\\\', '\\(', '\\)'],
            $text
        );
    }

    /**
     * ذخیره PDF در فایل
     * 
     * @param string $content محتوای PDF
     * @param string $filename مسیر فایل
     * @return bool موفقیت عملیات
     */
    public function saveToFile(string $content, string $filename): bool
    {
        $result = file_put_contents($filename, $content, LOCK_EX);
        return $result !== false;
    }

    /**
     * دانلود PDF به صورت HTTP
     * 
     * @param string $content محتوای PDF
     * @param string $filename نام فایل برای دانلود
     */
    public function download(string $content, string $filename): void
    {
        header('Content-Type: application/pdf');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . strlen($content));
        header('Cache-Control: no-cache, no-store, must-revalidate');
        header('Pragma: no-cache');
        header('Expires: 0');
        
        echo $content;
        exit;
    }

    /**
     * تنظیم اندازه صفحه
     * 
     * @param string $size اندازه صفحه (A4, Letter, etc.)
     */
    public function setPageSize(string $size): void
    {
        switch (strtoupper($size)) {
            case 'LETTER':
                $this->pageWidth = 612;
                $this->pageHeight = 792;
                break;
            case 'A4':
            default:
                $this->pageWidth = 595;
                $this->pageHeight = 842;
                break;
        }
    }
}
